apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

namePrefix: staging-

commonLabels:
  app: staging-dp-apis

resources:
- ../../base

images:
- name: DP-APIS-IMAGE
  newName: aimmo.azurecr.io/staging-dp-apis
  newTag: bdf4e1cb045323067a77d344ce66cefc1cf075e4

patches:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: apis-ingress
    version: v1
